version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  quizar:
    container_name: quizar
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app/alembic/versions:/app/alembic/versions
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 8080:80
